---
title: SSP Cloud avec R
subtitle: Utiliser le système de stockage
lang: fr
output:
  html_document:
    df_print: paged
params:
  bucket: f7sggu
---

#### Lister tous les buckets

Ceci est d'un intérêt limité sauf pour retrouver le nom de son bucket

```{r bucketlist}
bucket <- params$bucket

library(aws.s3)
bucketlist(region = "")
```

#### Lister les objets de son bucket

```{r list-objects-df}
objects <- get_bucket(bucket, region = "")

objects
```

#### Télécharger un fichier dans son espace de travail

```{r, eval=FALSE}
save_object(get_objectkey(objects[[2]]), bucket, region = "")
```

#### Déposer/Uploader un fichier sur son bucket

```{r, eval=FALSE}
file <- "s3.html"
put_object(file, file.path(basename(getwd()), file), bucket, region = "")
```

### Avec paws

Le package **paws** est de plus bas niveau. La configuration est :

```{r}
svc <- paws::s3(config = list(
  credentials = list(
    creds = list(
      access_key_id = Sys.getenv("AWS_ACCESS_KEY_ID"),
      secret_access_key = Sys.getenv("AWS_SECRET_ACCESS_KEY"),
      session_token = Sys.getenv("AWS_SESSION_TOKEN")
    ),
    profile = "f7sggu"
  ),
  endpoint = paste0("https://", Sys.getenv("AWS_S3_ENDPOINT")),
  region = Sys.getenv("AWS_DEFAULT_REGION")
))
```

```{r}
svc$list_objects_v2("f7sggu", Prefix = "sspcloud-demo")
```

---

### Infos

```{r, session}
git2r::repository()
```
